// Code generated by jsongen. DO NOT EDIT.

package eth

import (
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

func (x *Eth1Data) MarshalJSON() ([]byte, error) {
	type jsonRepresentation struct {
		DepositRoot  string `json:"deposit_root"`
		DepositCount string `json:"deposit_count"`
		BlockHash    string `json:"block_hash"`
	}
	return json.Marshal(&jsonRepresentation{
		DepositRoot:  hexutil.Encode(x.DepositRoot),
		DepositCount: fmt.Sprintf("%d", x.DepositCount),
		BlockHash:    hexutil.Encode(x.BlockHash),
	})
}

func (x *Eth1Data) UnmarshalJSON(enc []byte) error {
	type jsonRepresentation struct {
		DepositRoot  string `json:"deposit_root"`
		DepositCount string `json:"deposit_count"`
		BlockHash    string `json:"block_hash"`
	}
	var dec jsonRepresentation
	if err := json.Unmarshal(enc, &dec); err != nil {
		return err
	}
	{
		b, err := hexutil.Decode(dec.DepositRoot)
		if err != nil {
			return fmt.Errorf("invalid deposit_root: %w", err)
		}
		x.DepositRoot = b
	}
	{
		n, err := strconv.ParseUint(dec.DepositCount, 10, 64)
		if err != nil {
			return fmt.Errorf("invalid deposit_count: %w", err)
		}
		x.DepositCount = n
	}
	{
		b, err := hexutil.Decode(dec.BlockHash)
		if err != nil {
			return fmt.Errorf("invalid block_hash: %w", err)
		}
		x.BlockHash = b
	}
	return nil
}
