// Code generated by prysm-jsongen. DO NOT EDIT.

package eth

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	bitfield "github.com/OffchainLabs/go-bitfield"
	primitives "github.com/OffchainLabs/prysm/v7/consensus-types/primitives"
)

var _ = fmt.Sprint
var _ = strconv.FormatUint
var _ = strings.TrimPrefix
var _ = hex.EncodeToString

func (x *VoluntaryExit) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Epoch          string `json:"epoch"`
		ValidatorIndex string `json:"validator_index"`
	}
	o := &jsonObj{
		Epoch:          fmt.Sprintf("%d", x.Epoch),
		ValidatorIndex: fmt.Sprintf("%d", x.ValidatorIndex),
	}
	return json.Marshal(o)
}

func (x *VoluntaryExit) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Epoch          string `json:"epoch"`
		ValidatorIndex string `json:"validator_index"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.Epoch, 10, 64); err != nil {
		return err
	} else {
		x.Epoch = primitives.Epoch(v)
	}
	if v, err := strconv.ParseUint(o.ValidatorIndex, 10, 64); err != nil {
		return err
	} else {
		x.ValidatorIndex = primitives.ValidatorIndex(v)
	}
	return nil
}

func (x *Checkpoint) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Epoch string `json:"epoch"`
		Root  string `json:"root"`
	}
	o := &jsonObj{
		Epoch: fmt.Sprintf("%d", x.Epoch),
		Root:  "0x" + hex.EncodeToString(x.Root),
	}
	return json.Marshal(o)
}

func (x *Checkpoint) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Epoch string `json:"epoch"`
		Root  string `json:"root"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.Epoch, 10, 64); err != nil {
		return err
	} else {
		x.Epoch = primitives.Epoch(v)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Root, "0x")); err != nil {
		return err
	} else {
		x.Root = b
	}
	return nil
}

func (x *Fork) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		PreviousVersion string `json:"previous_version"`
		CurrentVersion  string `json:"current_version"`
		Epoch           string `json:"epoch"`
	}
	o := &jsonObj{
		PreviousVersion: "0x" + hex.EncodeToString(x.PreviousVersion),
		CurrentVersion:  "0x" + hex.EncodeToString(x.CurrentVersion),
		Epoch:           fmt.Sprintf("%d", x.Epoch),
	}
	return json.Marshal(o)
}

func (x *Fork) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		PreviousVersion string `json:"previous_version"`
		CurrentVersion  string `json:"current_version"`
		Epoch           string `json:"epoch"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.PreviousVersion, "0x")); err != nil {
		return err
	} else {
		x.PreviousVersion = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.CurrentVersion, "0x")); err != nil {
		return err
	} else {
		x.CurrentVersion = b
	}
	if v, err := strconv.ParseUint(o.Epoch, 10, 64); err != nil {
		return err
	} else {
		x.Epoch = primitives.Epoch(v)
	}
	return nil
}

func (x *AttestationData) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Slot            string      `json:"slot"`
		CommitteeIndex  string      `json:"index"`
		BeaconBlockRoot string      `json:"beacon_block_root"`
		Source          *Checkpoint `json:"source"`
		Target          *Checkpoint `json:"target"`
	}
	o := &jsonObj{
		Slot:            fmt.Sprintf("%d", x.Slot),
		CommitteeIndex:  fmt.Sprintf("%d", x.CommitteeIndex),
		BeaconBlockRoot: "0x" + hex.EncodeToString(x.BeaconBlockRoot),
		Source:          x.Source,
		Target:          x.Target,
	}
	return json.Marshal(o)
}

func (x *AttestationData) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Slot            string      `json:"slot"`
		CommitteeIndex  string      `json:"index"`
		BeaconBlockRoot string      `json:"beacon_block_root"`
		Source          *Checkpoint `json:"source"`
		Target          *Checkpoint `json:"target"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.Slot, 10, 64); err != nil {
		return err
	} else {
		x.Slot = primitives.Slot(v)
	}
	if v, err := strconv.ParseUint(o.CommitteeIndex, 10, 64); err != nil {
		return err
	} else {
		x.CommitteeIndex = primitives.CommitteeIndex(v)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.BeaconBlockRoot, "0x")); err != nil {
		return err
	} else {
		x.BeaconBlockRoot = b
	}
	x.Source = o.Source
	x.Target = o.Target
	return nil
}

func (x *BeaconBlockHeader) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Slot          string `json:"slot"`
		ProposerIndex string `json:"proposer_index"`
		ParentRoot    string `json:"parent_root"`
		StateRoot     string `json:"state_root"`
		BodyRoot      string `json:"body_root"`
	}
	o := &jsonObj{
		Slot:          fmt.Sprintf("%d", x.Slot),
		ProposerIndex: fmt.Sprintf("%d", x.ProposerIndex),
		ParentRoot:    "0x" + hex.EncodeToString(x.ParentRoot),
		StateRoot:     "0x" + hex.EncodeToString(x.StateRoot),
		BodyRoot:      "0x" + hex.EncodeToString(x.BodyRoot),
	}
	return json.Marshal(o)
}

func (x *BeaconBlockHeader) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Slot          string `json:"slot"`
		ProposerIndex string `json:"proposer_index"`
		ParentRoot    string `json:"parent_root"`
		StateRoot     string `json:"state_root"`
		BodyRoot      string `json:"body_root"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.Slot, 10, 64); err != nil {
		return err
	} else {
		x.Slot = primitives.Slot(v)
	}
	if v, err := strconv.ParseUint(o.ProposerIndex, 10, 64); err != nil {
		return err
	} else {
		x.ProposerIndex = primitives.ValidatorIndex(v)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.ParentRoot, "0x")); err != nil {
		return err
	} else {
		x.ParentRoot = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.StateRoot, "0x")); err != nil {
		return err
	} else {
		x.StateRoot = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.BodyRoot, "0x")); err != nil {
		return err
	} else {
		x.BodyRoot = b
	}
	return nil
}

func (x *SignedBeaconBlockHeader) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Header    *BeaconBlockHeader `json:"message"`
		Signature string             `json:"signature"`
	}
	o := &jsonObj{
		Header:    x.Header,
		Signature: "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SignedBeaconBlockHeader) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Header    *BeaconBlockHeader `json:"message"`
		Signature string             `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Header = o.Header
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *SignedVoluntaryExit) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Exit      *VoluntaryExit `json:"message"`
		Signature string         `json:"signature"`
	}
	o := &jsonObj{
		Exit:      x.Exit,
		Signature: "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SignedVoluntaryExit) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Exit      *VoluntaryExit `json:"message"`
		Signature string         `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Exit = o.Exit
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *ProposerSlashing) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Header_1 *SignedBeaconBlockHeader `json:"signed_header_1"`
		Header_2 *SignedBeaconBlockHeader `json:"signed_header_2"`
	}
	o := &jsonObj{
		Header_1: x.Header_1,
		Header_2: x.Header_2,
	}
	return json.Marshal(o)
}

func (x *ProposerSlashing) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Header_1 *SignedBeaconBlockHeader `json:"signed_header_1"`
		Header_2 *SignedBeaconBlockHeader `json:"signed_header_2"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Header_1 = o.Header_1
	x.Header_2 = o.Header_2
	return nil
}

func (x *Eth1Data) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		DepositRoot  string `json:"deposit_root"`
		DepositCount string `json:"deposit_count"`
		BlockHash    string `json:"block_hash"`
	}
	o := &jsonObj{
		DepositRoot:  "0x" + hex.EncodeToString(x.DepositRoot),
		DepositCount: fmt.Sprintf("%d", x.DepositCount),
		BlockHash:    "0x" + hex.EncodeToString(x.BlockHash),
	}
	return json.Marshal(o)
}

func (x *Eth1Data) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		DepositRoot  string `json:"deposit_root"`
		DepositCount string `json:"deposit_count"`
		BlockHash    string `json:"block_hash"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.DepositRoot, "0x")); err != nil {
		return err
	} else {
		x.DepositRoot = b
	}
	if v, err := strconv.ParseUint(o.DepositCount, 10, 64); err != nil {
		return err
	} else {
		x.DepositCount = v
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.BlockHash, "0x")); err != nil {
		return err
	} else {
		x.BlockHash = b
	}
	return nil
}

func (x *Validator) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		PublicKey                  string `json:"pubkey"`
		WithdrawalCredentials      string `json:"withdrawal_credentials"`
		EffectiveBalance           string `json:"effective_balance"`
		Slashed                    bool   `json:"slashed"`
		ActivationEligibilityEpoch string `json:"activation_eligibility_epoch"`
		ActivationEpoch            string `json:"activation_epoch"`
		ExitEpoch                  string `json:"exit_epoch"`
		WithdrawableEpoch          string `json:"withdrawable_epoch"`
	}
	o := &jsonObj{
		PublicKey:                  "0x" + hex.EncodeToString(x.PublicKey),
		WithdrawalCredentials:      "0x" + hex.EncodeToString(x.WithdrawalCredentials),
		EffectiveBalance:           fmt.Sprintf("%d", x.EffectiveBalance),
		Slashed:                    x.Slashed,
		ActivationEligibilityEpoch: fmt.Sprintf("%d", x.ActivationEligibilityEpoch),
		ActivationEpoch:            fmt.Sprintf("%d", x.ActivationEpoch),
		ExitEpoch:                  fmt.Sprintf("%d", x.ExitEpoch),
		WithdrawableEpoch:          fmt.Sprintf("%d", x.WithdrawableEpoch),
	}
	return json.Marshal(o)
}

func (x *Validator) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		PublicKey                  string `json:"pubkey"`
		WithdrawalCredentials      string `json:"withdrawal_credentials"`
		EffectiveBalance           string `json:"effective_balance"`
		Slashed                    bool   `json:"slashed"`
		ActivationEligibilityEpoch string `json:"activation_eligibility_epoch"`
		ActivationEpoch            string `json:"activation_epoch"`
		ExitEpoch                  string `json:"exit_epoch"`
		WithdrawableEpoch          string `json:"withdrawable_epoch"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.PublicKey, "0x")); err != nil {
		return err
	} else {
		x.PublicKey = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.WithdrawalCredentials, "0x")); err != nil {
		return err
	} else {
		x.WithdrawalCredentials = b
	}
	if v, err := strconv.ParseUint(o.EffectiveBalance, 10, 64); err != nil {
		return err
	} else {
		x.EffectiveBalance = v
	}
	x.Slashed = o.Slashed
	if v, err := strconv.ParseUint(o.ActivationEligibilityEpoch, 10, 64); err != nil {
		return err
	} else {
		x.ActivationEligibilityEpoch = primitives.Epoch(v)
	}
	if v, err := strconv.ParseUint(o.ActivationEpoch, 10, 64); err != nil {
		return err
	} else {
		x.ActivationEpoch = primitives.Epoch(v)
	}
	if v, err := strconv.ParseUint(o.ExitEpoch, 10, 64); err != nil {
		return err
	} else {
		x.ExitEpoch = primitives.Epoch(v)
	}
	if v, err := strconv.ParseUint(o.WithdrawableEpoch, 10, 64); err != nil {
		return err
	} else {
		x.WithdrawableEpoch = primitives.Epoch(v)
	}
	return nil
}

func (x *IndexedAttestation) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		AttestingIndices []string         `json:"attesting_indices"`
		Data             *AttestationData `json:"data"`
		Signature        string           `json:"signature"`
	}
	AttestingIndicesJSON := make([]string, len(x.AttestingIndices))
	for i, v := range x.AttestingIndices {
		AttestingIndicesJSON[i] = fmt.Sprintf("%d", v)
	}
	o := &jsonObj{
		AttestingIndices: AttestingIndicesJSON,
		Data:             x.Data,
		Signature:        "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *IndexedAttestation) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		AttestingIndices []string         `json:"attesting_indices"`
		Data             *AttestationData `json:"data"`
		Signature        string           `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.AttestingIndices = make([]uint64, len(o.AttestingIndices))
	for i, s := range o.AttestingIndices {
		v, err := strconv.ParseUint(s, 10, 64)
		if err != nil {
			return err
		}
		x.AttestingIndices[i] = v
	}
	x.Data = o.Data
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *AttesterSlashing) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Attestation_1 *IndexedAttestation `json:"attestation_1"`
		Attestation_2 *IndexedAttestation `json:"attestation_2"`
	}
	o := &jsonObj{
		Attestation_1: x.Attestation_1,
		Attestation_2: x.Attestation_2,
	}
	return json.Marshal(o)
}

func (x *AttesterSlashing) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Attestation_1 *IndexedAttestation `json:"attestation_1"`
		Attestation_2 *IndexedAttestation `json:"attestation_2"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Attestation_1 = o.Attestation_1
	x.Attestation_2 = o.Attestation_2
	return nil
}

func (x *SyncCommittee) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Pubkeys         []string `json:"pubkeys"`
		AggregatePubkey string   `json:"aggregate_pubkey"`
	}
	PubkeysJSON := make([]string, len(x.Pubkeys))
	for i, v := range x.Pubkeys {
		PubkeysJSON[i] = "0x" + hex.EncodeToString(v)
	}
	o := &jsonObj{
		Pubkeys:         PubkeysJSON,
		AggregatePubkey: "0x" + hex.EncodeToString(x.AggregatePubkey),
	}
	return json.Marshal(o)
}

func (x *SyncCommittee) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Pubkeys         []string `json:"pubkeys"`
		AggregatePubkey string   `json:"aggregate_pubkey"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Pubkeys = make([][]byte, len(o.Pubkeys))
	for i, s := range o.Pubkeys {
		b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
		if err != nil {
			return err
		}
		x.Pubkeys[i] = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.AggregatePubkey, "0x")); err != nil {
		return err
	} else {
		x.AggregatePubkey = b
	}
	return nil
}

func (x *BLSToExecutionChange) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		ValidatorIndex     string `json:"validator_index"`
		FromBlsPubkey      string `json:"from_bls_pubkey"`
		ToExecutionAddress string `json:"to_execution_address"`
	}
	o := &jsonObj{
		ValidatorIndex:     fmt.Sprintf("%d", x.ValidatorIndex),
		FromBlsPubkey:      "0x" + hex.EncodeToString(x.FromBlsPubkey),
		ToExecutionAddress: "0x" + hex.EncodeToString(x.ToExecutionAddress),
	}
	return json.Marshal(o)
}

func (x *BLSToExecutionChange) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		ValidatorIndex     string `json:"validator_index"`
		FromBlsPubkey      string `json:"from_bls_pubkey"`
		ToExecutionAddress string `json:"to_execution_address"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.ValidatorIndex, 10, 64); err != nil {
		return err
	} else {
		x.ValidatorIndex = primitives.ValidatorIndex(v)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.FromBlsPubkey, "0x")); err != nil {
		return err
	} else {
		x.FromBlsPubkey = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.ToExecutionAddress, "0x")); err != nil {
		return err
	} else {
		x.ToExecutionAddress = b
	}
	return nil
}

func (x *SignedBLSToExecutionChange) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Message   *BLSToExecutionChange `json:"message"`
		Signature string                `json:"signature"`
	}
	o := &jsonObj{
		Message:   x.Message,
		Signature: "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SignedBLSToExecutionChange) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Message   *BLSToExecutionChange `json:"message"`
		Signature string                `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Message = o.Message
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *HistoricalSummary) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		BlockSummaryRoot string `json:"block_summary_root"`
		StateSummaryRoot string `json:"state_summary_root"`
	}
	o := &jsonObj{
		BlockSummaryRoot: "0x" + hex.EncodeToString(x.BlockSummaryRoot),
		StateSummaryRoot: "0x" + hex.EncodeToString(x.StateSummaryRoot),
	}
	return json.Marshal(o)
}

func (x *HistoricalSummary) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		BlockSummaryRoot string `json:"block_summary_root"`
		StateSummaryRoot string `json:"state_summary_root"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.BlockSummaryRoot, "0x")); err != nil {
		return err
	} else {
		x.BlockSummaryRoot = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.StateSummaryRoot, "0x")); err != nil {
		return err
	} else {
		x.StateSummaryRoot = b
	}
	return nil
}

func (x *BeaconBlock) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Slot          string           `json:"slot"`
		ProposerIndex string           `json:"proposer_index"`
		ParentRoot    string           `json:"parent_root"`
		StateRoot     string           `json:"state_root"`
		Body          *BeaconBlockBody `json:"body"`
	}
	o := &jsonObj{
		Slot:          fmt.Sprintf("%d", x.Slot),
		ProposerIndex: fmt.Sprintf("%d", x.ProposerIndex),
		ParentRoot:    "0x" + hex.EncodeToString(x.ParentRoot),
		StateRoot:     "0x" + hex.EncodeToString(x.StateRoot),
		Body:          x.Body,
	}
	return json.Marshal(o)
}

func (x *BeaconBlock) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Slot          string           `json:"slot"`
		ProposerIndex string           `json:"proposer_index"`
		ParentRoot    string           `json:"parent_root"`
		StateRoot     string           `json:"state_root"`
		Body          *BeaconBlockBody `json:"body"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.Slot, 10, 64); err != nil {
		return err
	} else {
		x.Slot = primitives.Slot(v)
	}
	if v, err := strconv.ParseUint(o.ProposerIndex, 10, 64); err != nil {
		return err
	} else {
		x.ProposerIndex = primitives.ValidatorIndex(v)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.ParentRoot, "0x")); err != nil {
		return err
	} else {
		x.ParentRoot = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.StateRoot, "0x")); err != nil {
		return err
	} else {
		x.StateRoot = b
	}
	x.Body = o.Body
	return nil
}

func (x *BeaconBlockBody) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		RandaoReveal      string                 `json:"randao_reveal"`
		Eth1Data          *Eth1Data              `json:"eth1_data"`
		Graffiti          string                 `json:"graffiti"`
		ProposerSlashings []*ProposerSlashing    `json:"proposer_slashings"`
		AttesterSlashings []*AttesterSlashing    `json:"attester_slashings"`
		Attestations      []*Attestation         `json:"attestations"`
		Deposits          []*Deposit             `json:"deposits"`
		VoluntaryExits    []*SignedVoluntaryExit `json:"voluntary_exits"`
	}
	o := &jsonObj{
		RandaoReveal:      "0x" + hex.EncodeToString(x.RandaoReveal),
		Eth1Data:          x.Eth1Data,
		Graffiti:          "0x" + hex.EncodeToString(x.Graffiti),
		ProposerSlashings: x.ProposerSlashings,
		AttesterSlashings: x.AttesterSlashings,
		Attestations:      x.Attestations,
		Deposits:          x.Deposits,
		VoluntaryExits:    x.VoluntaryExits,
	}
	return json.Marshal(o)
}

func (x *BeaconBlockBody) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		RandaoReveal      string                 `json:"randao_reveal"`
		Eth1Data          *Eth1Data              `json:"eth1_data"`
		Graffiti          string                 `json:"graffiti"`
		ProposerSlashings []*ProposerSlashing    `json:"proposer_slashings"`
		AttesterSlashings []*AttesterSlashing    `json:"attester_slashings"`
		Attestations      []*Attestation         `json:"attestations"`
		Deposits          []*Deposit             `json:"deposits"`
		VoluntaryExits    []*SignedVoluntaryExit `json:"voluntary_exits"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.RandaoReveal, "0x")); err != nil {
		return err
	} else {
		x.RandaoReveal = b
	}
	x.Eth1Data = o.Eth1Data
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Graffiti, "0x")); err != nil {
		return err
	} else {
		x.Graffiti = b
	}
	x.ProposerSlashings = o.ProposerSlashings
	x.AttesterSlashings = o.AttesterSlashings
	x.Attestations = o.Attestations
	x.Deposits = o.Deposits
	x.VoluntaryExits = o.VoluntaryExits
	return nil
}

func (x *Deposit) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Proof []string      `json:"proof"`
		Data  *Deposit_Data `json:"data"`
	}
	ProofJSON := make([]string, len(x.Proof))
	for i, v := range x.Proof {
		ProofJSON[i] = "0x" + hex.EncodeToString(v)
	}
	o := &jsonObj{
		Proof: ProofJSON,
		Data:  x.Data,
	}
	return json.Marshal(o)
}

func (x *Deposit) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Proof []string      `json:"proof"`
		Data  *Deposit_Data `json:"data"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Proof = make([][]byte, len(o.Proof))
	for i, s := range o.Proof {
		b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
		if err != nil {
			return err
		}
		x.Proof[i] = b
	}
	x.Data = o.Data
	return nil
}

func (x *Deposit_Data) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		PublicKey             string `json:"pubkey"`
		WithdrawalCredentials string `json:"withdrawal_credentials"`
		Amount                string `json:"amount"`
		Signature             string `json:"signature"`
	}
	o := &jsonObj{
		PublicKey:             "0x" + hex.EncodeToString(x.PublicKey),
		WithdrawalCredentials: "0x" + hex.EncodeToString(x.WithdrawalCredentials),
		Amount:                fmt.Sprintf("%d", x.Amount),
		Signature:             "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *Deposit_Data) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		PublicKey             string `json:"pubkey"`
		WithdrawalCredentials string `json:"withdrawal_credentials"`
		Amount                string `json:"amount"`
		Signature             string `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.PublicKey, "0x")); err != nil {
		return err
	} else {
		x.PublicKey = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.WithdrawalCredentials, "0x")); err != nil {
		return err
	} else {
		x.WithdrawalCredentials = b
	}
	if v, err := strconv.ParseUint(o.Amount, 10, 64); err != nil {
		return err
	} else {
		x.Amount = v
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *Attestation) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		AggregationBits string           `json:"aggregation_bits"`
		Data            *AttestationData `json:"data"`
		Signature       string           `json:"signature"`
	}
	o := &jsonObj{
		AggregationBits: "0x" + hex.EncodeToString(x.AggregationBits),
		Data:            x.Data,
		Signature:       "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *Attestation) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		AggregationBits string           `json:"aggregation_bits"`
		Data            *AttestationData `json:"data"`
		Signature       string           `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.AggregationBits, "0x")); err != nil {
		return err
	} else {
		x.AggregationBits = bitfield.Bitlist(b)
	}
	x.Data = o.Data
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *SyncAggregate) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		SyncCommitteeBits      string `json:"sync_committee_bits"`
		SyncCommitteeSignature string `json:"sync_committee_signature"`
	}
	o := &jsonObj{
		SyncCommitteeBits:      "0x" + hex.EncodeToString(x.SyncCommitteeBits),
		SyncCommitteeSignature: "0x" + hex.EncodeToString(x.SyncCommitteeSignature),
	}
	return json.Marshal(o)
}

func (x *SyncAggregate) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		SyncCommitteeBits      string `json:"sync_committee_bits"`
		SyncCommitteeSignature string `json:"sync_committee_signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.SyncCommitteeBits, "0x")); err != nil {
		return err
	} else {
		x.SyncCommitteeBits = bitfield.Bitvector512(b)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.SyncCommitteeSignature, "0x")); err != nil {
		return err
	} else {
		x.SyncCommitteeSignature = b
	}
	return nil
}

func (x *BeaconState) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		GenesisTime                 string                `json:"genesis_time"`
		GenesisValidatorsRoot       string                `json:"genesis_validators_root"`
		Slot                        string                `json:"slot"`
		Fork                        *Fork                 `json:"fork"`
		LatestBlockHeader           *BeaconBlockHeader    `json:"latest_block_header"`
		BlockRoots                  []string              `json:"block_roots"`
		StateRoots                  []string              `json:"state_roots"`
		HistoricalRoots             []string              `json:"historical_roots"`
		Eth1Data                    *Eth1Data             `json:"eth1_data"`
		Eth1DataVotes               []*Eth1Data           `json:"eth1_data_votes"`
		Eth1DepositIndex            string                `json:"eth1_deposit_index"`
		Validators                  []*Validator          `json:"validators"`
		Balances                    []string              `json:"balances"`
		RandaoMixes                 []string              `json:"randao_mixes"`
		Slashings                   []string              `json:"slashings"`
		PreviousEpochAttestations   []*PendingAttestation `json:"previous_epoch_attestations"`
		CurrentEpochAttestations    []*PendingAttestation `json:"current_epoch_attestations"`
		JustificationBits           string                `json:"justification_bits"`
		PreviousJustifiedCheckpoint *Checkpoint           `json:"previous_justified_checkpoint"`
		CurrentJustifiedCheckpoint  *Checkpoint           `json:"current_justified_checkpoint"`
		FinalizedCheckpoint         *Checkpoint           `json:"finalized_checkpoint"`
	}
	BlockRootsJSON := make([]string, len(x.BlockRoots))
	for i, v := range x.BlockRoots {
		BlockRootsJSON[i] = "0x" + hex.EncodeToString(v)
	}
	StateRootsJSON := make([]string, len(x.StateRoots))
	for i, v := range x.StateRoots {
		StateRootsJSON[i] = "0x" + hex.EncodeToString(v)
	}
	HistoricalRootsJSON := make([]string, len(x.HistoricalRoots))
	for i, v := range x.HistoricalRoots {
		HistoricalRootsJSON[i] = "0x" + hex.EncodeToString(v)
	}
	BalancesJSON := make([]string, len(x.Balances))
	for i, v := range x.Balances {
		BalancesJSON[i] = fmt.Sprintf("%d", v)
	}
	RandaoMixesJSON := make([]string, len(x.RandaoMixes))
	for i, v := range x.RandaoMixes {
		RandaoMixesJSON[i] = "0x" + hex.EncodeToString(v)
	}
	SlashingsJSON := make([]string, len(x.Slashings))
	for i, v := range x.Slashings {
		SlashingsJSON[i] = fmt.Sprintf("%d", v)
	}
	o := &jsonObj{
		GenesisTime:                 fmt.Sprintf("%d", x.GenesisTime),
		GenesisValidatorsRoot:       "0x" + hex.EncodeToString(x.GenesisValidatorsRoot),
		Slot:                        fmt.Sprintf("%d", x.Slot),
		Fork:                        x.Fork,
		LatestBlockHeader:           x.LatestBlockHeader,
		BlockRoots:                  BlockRootsJSON,
		StateRoots:                  StateRootsJSON,
		HistoricalRoots:             HistoricalRootsJSON,
		Eth1Data:                    x.Eth1Data,
		Eth1DataVotes:               x.Eth1DataVotes,
		Eth1DepositIndex:            fmt.Sprintf("%d", x.Eth1DepositIndex),
		Validators:                  x.Validators,
		Balances:                    BalancesJSON,
		RandaoMixes:                 RandaoMixesJSON,
		Slashings:                   SlashingsJSON,
		PreviousEpochAttestations:   x.PreviousEpochAttestations,
		CurrentEpochAttestations:    x.CurrentEpochAttestations,
		JustificationBits:           "0x" + hex.EncodeToString(x.JustificationBits),
		PreviousJustifiedCheckpoint: x.PreviousJustifiedCheckpoint,
		CurrentJustifiedCheckpoint:  x.CurrentJustifiedCheckpoint,
		FinalizedCheckpoint:         x.FinalizedCheckpoint,
	}
	return json.Marshal(o)
}

func (x *BeaconState) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		GenesisTime                 string                `json:"genesis_time"`
		GenesisValidatorsRoot       string                `json:"genesis_validators_root"`
		Slot                        string                `json:"slot"`
		Fork                        *Fork                 `json:"fork"`
		LatestBlockHeader           *BeaconBlockHeader    `json:"latest_block_header"`
		BlockRoots                  []string              `json:"block_roots"`
		StateRoots                  []string              `json:"state_roots"`
		HistoricalRoots             []string              `json:"historical_roots"`
		Eth1Data                    *Eth1Data             `json:"eth1_data"`
		Eth1DataVotes               []*Eth1Data           `json:"eth1_data_votes"`
		Eth1DepositIndex            string                `json:"eth1_deposit_index"`
		Validators                  []*Validator          `json:"validators"`
		Balances                    []string              `json:"balances"`
		RandaoMixes                 []string              `json:"randao_mixes"`
		Slashings                   []string              `json:"slashings"`
		PreviousEpochAttestations   []*PendingAttestation `json:"previous_epoch_attestations"`
		CurrentEpochAttestations    []*PendingAttestation `json:"current_epoch_attestations"`
		JustificationBits           string                `json:"justification_bits"`
		PreviousJustifiedCheckpoint *Checkpoint           `json:"previous_justified_checkpoint"`
		CurrentJustifiedCheckpoint  *Checkpoint           `json:"current_justified_checkpoint"`
		FinalizedCheckpoint         *Checkpoint           `json:"finalized_checkpoint"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.GenesisTime, 10, 64); err != nil {
		return err
	} else {
		x.GenesisTime = v
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.GenesisValidatorsRoot, "0x")); err != nil {
		return err
	} else {
		x.GenesisValidatorsRoot = b
	}
	if v, err := strconv.ParseUint(o.Slot, 10, 64); err != nil {
		return err
	} else {
		x.Slot = primitives.Slot(v)
	}
	x.Fork = o.Fork
	x.LatestBlockHeader = o.LatestBlockHeader
	x.BlockRoots = make([][]byte, len(o.BlockRoots))
	for i, s := range o.BlockRoots {
		b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
		if err != nil {
			return err
		}
		x.BlockRoots[i] = b
	}
	x.StateRoots = make([][]byte, len(o.StateRoots))
	for i, s := range o.StateRoots {
		b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
		if err != nil {
			return err
		}
		x.StateRoots[i] = b
	}
	x.HistoricalRoots = make([][]byte, len(o.HistoricalRoots))
	for i, s := range o.HistoricalRoots {
		b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
		if err != nil {
			return err
		}
		x.HistoricalRoots[i] = b
	}
	x.Eth1Data = o.Eth1Data
	x.Eth1DataVotes = o.Eth1DataVotes
	if v, err := strconv.ParseUint(o.Eth1DepositIndex, 10, 64); err != nil {
		return err
	} else {
		x.Eth1DepositIndex = v
	}
	x.Validators = o.Validators
	x.Balances = make([]uint64, len(o.Balances))
	for i, s := range o.Balances {
		v, err := strconv.ParseUint(s, 10, 64)
		if err != nil {
			return err
		}
		x.Balances[i] = v
	}
	x.RandaoMixes = make([][]byte, len(o.RandaoMixes))
	for i, s := range o.RandaoMixes {
		b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
		if err != nil {
			return err
		}
		x.RandaoMixes[i] = b
	}
	x.Slashings = make([]uint64, len(o.Slashings))
	for i, s := range o.Slashings {
		v, err := strconv.ParseUint(s, 10, 64)
		if err != nil {
			return err
		}
		x.Slashings[i] = v
	}
	x.PreviousEpochAttestations = o.PreviousEpochAttestations
	x.CurrentEpochAttestations = o.CurrentEpochAttestations
	if b, err := hex.DecodeString(strings.TrimPrefix(o.JustificationBits, "0x")); err != nil {
		return err
	} else {
		x.JustificationBits = bitfield.Bitvector4(b)
	}
	x.PreviousJustifiedCheckpoint = o.PreviousJustifiedCheckpoint
	x.CurrentJustifiedCheckpoint = o.CurrentJustifiedCheckpoint
	x.FinalizedCheckpoint = o.FinalizedCheckpoint
	return nil
}

func (x *PendingAttestation) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		AggregationBits string           `json:"aggregation_bits"`
		Data            *AttestationData `json:"data"`
		InclusionDelay  string           `json:"inclusion_delay"`
		ProposerIndex   string           `json:"proposer_index"`
	}
	o := &jsonObj{
		AggregationBits: "0x" + hex.EncodeToString(x.AggregationBits),
		Data:            x.Data,
		InclusionDelay:  fmt.Sprintf("%d", x.InclusionDelay),
		ProposerIndex:   fmt.Sprintf("%d", x.ProposerIndex),
	}
	return json.Marshal(o)
}

func (x *PendingAttestation) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		AggregationBits string           `json:"aggregation_bits"`
		Data            *AttestationData `json:"data"`
		InclusionDelay  string           `json:"inclusion_delay"`
		ProposerIndex   string           `json:"proposer_index"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.AggregationBits, "0x")); err != nil {
		return err
	} else {
		x.AggregationBits = bitfield.Bitlist(b)
	}
	x.Data = o.Data
	if v, err := strconv.ParseUint(o.InclusionDelay, 10, 64); err != nil {
		return err
	} else {
		x.InclusionDelay = primitives.Slot(v)
	}
	if v, err := strconv.ParseUint(o.ProposerIndex, 10, 64); err != nil {
		return err
	} else {
		x.ProposerIndex = primitives.ValidatorIndex(v)
	}
	return nil
}

func (x *SingleAttestation) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		CommitteeId   string           `json:"committee_index"`
		AttesterIndex string           `json:"attester_index"`
		Data          *AttestationData `json:"data"`
		Signature     string           `json:"signature"`
	}
	o := &jsonObj{
		CommitteeId:   fmt.Sprintf("%d", x.CommitteeId),
		AttesterIndex: fmt.Sprintf("%d", x.AttesterIndex),
		Data:          x.Data,
		Signature:     "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SingleAttestation) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		CommitteeId   string           `json:"committee_index"`
		AttesterIndex string           `json:"attester_index"`
		Data          *AttestationData `json:"data"`
		Signature     string           `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.CommitteeId, 10, 64); err != nil {
		return err
	} else {
		x.CommitteeId = primitives.CommitteeIndex(v)
	}
	if v, err := strconv.ParseUint(o.AttesterIndex, 10, 64); err != nil {
		return err
	} else {
		x.AttesterIndex = primitives.ValidatorIndex(v)
	}
	x.Data = o.Data
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *AttestationElectra) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		AggregationBits string           `json:"aggregation_bits"`
		Data            *AttestationData `json:"data"`
		Signature       string           `json:"signature"`
		CommitteeBits   string           `json:"committee_bits"`
	}
	o := &jsonObj{
		AggregationBits: "0x" + hex.EncodeToString(x.AggregationBits),
		Data:            x.Data,
		Signature:       "0x" + hex.EncodeToString(x.Signature),
		CommitteeBits:   "0x" + hex.EncodeToString(x.CommitteeBits),
	}
	return json.Marshal(o)
}

func (x *AttestationElectra) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		AggregationBits string           `json:"aggregation_bits"`
		Data            *AttestationData `json:"data"`
		Signature       string           `json:"signature"`
		CommitteeBits   string           `json:"committee_bits"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.AggregationBits, "0x")); err != nil {
		return err
	} else {
		x.AggregationBits = bitfield.Bitlist(b)
	}
	x.Data = o.Data
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.CommitteeBits, "0x")); err != nil {
		return err
	} else {
		x.CommitteeBits = bitfield.Bitvector64(b)
	}
	return nil
}

func (x *IndexedAttestationElectra) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		AttestingIndices []string         `json:"attesting_indices"`
		Data             *AttestationData `json:"data"`
		Signature        string           `json:"signature"`
	}
	AttestingIndicesJSON := make([]string, len(x.AttestingIndices))
	for i, v := range x.AttestingIndices {
		AttestingIndicesJSON[i] = fmt.Sprintf("%d", v)
	}
	o := &jsonObj{
		AttestingIndices: AttestingIndicesJSON,
		Data:             x.Data,
		Signature:        "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *IndexedAttestationElectra) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		AttestingIndices []string         `json:"attesting_indices"`
		Data             *AttestationData `json:"data"`
		Signature        string           `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.AttestingIndices = make([]uint64, len(o.AttestingIndices))
	for i, s := range o.AttestingIndices {
		v, err := strconv.ParseUint(s, 10, 64)
		if err != nil {
			return err
		}
		x.AttestingIndices[i] = v
	}
	x.Data = o.Data
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *AttesterSlashingElectra) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Attestation_1 *IndexedAttestationElectra `json:"attestation_1"`
		Attestation_2 *IndexedAttestationElectra `json:"attestation_2"`
	}
	o := &jsonObj{
		Attestation_1: x.Attestation_1,
		Attestation_2: x.Attestation_2,
	}
	return json.Marshal(o)
}

func (x *AttesterSlashingElectra) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Attestation_1 *IndexedAttestationElectra `json:"attestation_1"`
		Attestation_2 *IndexedAttestationElectra `json:"attestation_2"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Attestation_1 = o.Attestation_1
	x.Attestation_2 = o.Attestation_2
	return nil
}

func (x *PendingDeposit) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		PublicKey             string `json:"pubkey"`
		WithdrawalCredentials string `json:"withdrawal_credentials"`
		Amount                string `json:"amount"`
		Signature             string `json:"signature"`
		Slot                  string `json:"slot"`
	}
	o := &jsonObj{
		PublicKey:             "0x" + hex.EncodeToString(x.PublicKey),
		WithdrawalCredentials: "0x" + hex.EncodeToString(x.WithdrawalCredentials),
		Amount:                fmt.Sprintf("%d", x.Amount),
		Signature:             "0x" + hex.EncodeToString(x.Signature),
		Slot:                  fmt.Sprintf("%d", x.Slot),
	}
	return json.Marshal(o)
}

func (x *PendingDeposit) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		PublicKey             string `json:"pubkey"`
		WithdrawalCredentials string `json:"withdrawal_credentials"`
		Amount                string `json:"amount"`
		Signature             string `json:"signature"`
		Slot                  string `json:"slot"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.PublicKey, "0x")); err != nil {
		return err
	} else {
		x.PublicKey = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.WithdrawalCredentials, "0x")); err != nil {
		return err
	} else {
		x.WithdrawalCredentials = b
	}
	if v, err := strconv.ParseUint(o.Amount, 10, 64); err != nil {
		return err
	} else {
		x.Amount = v
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	if v, err := strconv.ParseUint(o.Slot, 10, 64); err != nil {
		return err
	} else {
		x.Slot = primitives.Slot(v)
	}
	return nil
}

func (x *PendingPartialWithdrawal) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Index             string `json:"index"`
		Amount            string `json:"amount"`
		WithdrawableEpoch string `json:"withdrawable_epoch"`
	}
	o := &jsonObj{
		Index:             fmt.Sprintf("%d", x.Index),
		Amount:            fmt.Sprintf("%d", x.Amount),
		WithdrawableEpoch: fmt.Sprintf("%d", x.WithdrawableEpoch),
	}
	return json.Marshal(o)
}

func (x *PendingPartialWithdrawal) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Index             string `json:"index"`
		Amount            string `json:"amount"`
		WithdrawableEpoch string `json:"withdrawable_epoch"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.Index, 10, 64); err != nil {
		return err
	} else {
		x.Index = primitives.ValidatorIndex(v)
	}
	if v, err := strconv.ParseUint(o.Amount, 10, 64); err != nil {
		return err
	} else {
		x.Amount = v
	}
	if v, err := strconv.ParseUint(o.WithdrawableEpoch, 10, 64); err != nil {
		return err
	} else {
		x.WithdrawableEpoch = primitives.Epoch(v)
	}
	return nil
}

func (x *PendingConsolidation) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		SourceIndex string `json:"source_index"`
		TargetIndex string `json:"target_index"`
	}
	o := &jsonObj{
		SourceIndex: fmt.Sprintf("%d", x.SourceIndex),
		TargetIndex: fmt.Sprintf("%d", x.TargetIndex),
	}
	return json.Marshal(o)
}

func (x *PendingConsolidation) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		SourceIndex string `json:"source_index"`
		TargetIndex string `json:"target_index"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.SourceIndex, 10, 64); err != nil {
		return err
	} else {
		x.SourceIndex = primitives.ValidatorIndex(v)
	}
	if v, err := strconv.ParseUint(o.TargetIndex, 10, 64); err != nil {
		return err
	} else {
		x.TargetIndex = primitives.ValidatorIndex(v)
	}
	return nil
}

func (x *SyncCommitteeContribution) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Slot              string `json:"slot"`
		BlockRoot         string `json:"beacon_block_root"`
		SubcommitteeIndex string `json:"subcommittee_index"`
		AggregationBits   string `json:"aggregation_bits"`
		Signature         string `json:"signature"`
	}
	o := &jsonObj{
		Slot:              fmt.Sprintf("%d", x.Slot),
		BlockRoot:         "0x" + hex.EncodeToString(x.BlockRoot),
		SubcommitteeIndex: fmt.Sprintf("%d", x.SubcommitteeIndex),
		AggregationBits:   "0x" + hex.EncodeToString(x.AggregationBits),
		Signature:         "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SyncCommitteeContribution) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Slot              string `json:"slot"`
		BlockRoot         string `json:"beacon_block_root"`
		SubcommitteeIndex string `json:"subcommittee_index"`
		AggregationBits   string `json:"aggregation_bits"`
		Signature         string `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.Slot, 10, 64); err != nil {
		return err
	} else {
		x.Slot = primitives.Slot(v)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.BlockRoot, "0x")); err != nil {
		return err
	} else {
		x.BlockRoot = b
	}
	if v, err := strconv.ParseUint(o.SubcommitteeIndex, 10, 64); err != nil {
		return err
	} else {
		x.SubcommitteeIndex = v
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.AggregationBits, "0x")); err != nil {
		return err
	} else {
		x.AggregationBits = bitfield.Bitvector128(b)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *ContributionAndProof) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		AggregatorIndex string                     `json:"aggregator_index"`
		Contribution    *SyncCommitteeContribution `json:"contribution"`
		SelectionProof  string                     `json:"selection_proof"`
	}
	o := &jsonObj{
		AggregatorIndex: fmt.Sprintf("%d", x.AggregatorIndex),
		Contribution:    x.Contribution,
		SelectionProof:  "0x" + hex.EncodeToString(x.SelectionProof),
	}
	return json.Marshal(o)
}

func (x *ContributionAndProof) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		AggregatorIndex string                     `json:"aggregator_index"`
		Contribution    *SyncCommitteeContribution `json:"contribution"`
		SelectionProof  string                     `json:"selection_proof"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.AggregatorIndex, 10, 64); err != nil {
		return err
	} else {
		x.AggregatorIndex = primitives.ValidatorIndex(v)
	}
	x.Contribution = o.Contribution
	if b, err := hex.DecodeString(strings.TrimPrefix(o.SelectionProof, "0x")); err != nil {
		return err
	} else {
		x.SelectionProof = b
	}
	return nil
}

func (x *SignedContributionAndProof) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Message   *ContributionAndProof `json:"message"`
		Signature string                `json:"signature"`
	}
	o := &jsonObj{
		Message:   x.Message,
		Signature: "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SignedContributionAndProof) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Message   *ContributionAndProof `json:"message"`
		Signature string                `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Message = o.Message
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *ValidatorRegistrationV1) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		FeeRecipient string `json:"fee_recipient"`
		GasLimit     string `json:"gas_limit"`
		Timestamp    string `json:"timestamp"`
		Pubkey       string `json:"pubkey"`
	}
	o := &jsonObj{
		FeeRecipient: "0x" + hex.EncodeToString(x.FeeRecipient),
		GasLimit:     fmt.Sprintf("%d", x.GasLimit),
		Timestamp:    fmt.Sprintf("%d", x.Timestamp),
		Pubkey:       "0x" + hex.EncodeToString(x.Pubkey),
	}
	return json.Marshal(o)
}

func (x *ValidatorRegistrationV1) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		FeeRecipient string `json:"fee_recipient"`
		GasLimit     string `json:"gas_limit"`
		Timestamp    string `json:"timestamp"`
		Pubkey       string `json:"pubkey"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.FeeRecipient, "0x")); err != nil {
		return err
	} else {
		x.FeeRecipient = b
	}
	if v, err := strconv.ParseUint(o.GasLimit, 10, 64); err != nil {
		return err
	} else {
		x.GasLimit = v
	}
	if v, err := strconv.ParseUint(o.Timestamp, 10, 64); err != nil {
		return err
	} else {
		x.Timestamp = v
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Pubkey, "0x")); err != nil {
		return err
	} else {
		x.Pubkey = b
	}
	return nil
}

func (x *SignedValidatorRegistrationV1) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Message   *ValidatorRegistrationV1 `json:"message"`
		Signature string                   `json:"signature"`
	}
	o := &jsonObj{
		Message:   x.Message,
		Signature: "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SignedValidatorRegistrationV1) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Message   *ValidatorRegistrationV1 `json:"message"`
		Signature string                   `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Message = o.Message
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *PayloadAttestation) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		AggregationBits string                  `json:"aggregation_bits"`
		Data            *PayloadAttestationData `json:"data"`
		Signature       string                  `json:"signature"`
	}
	o := &jsonObj{
		AggregationBits: "0x" + hex.EncodeToString(x.AggregationBits),
		Data:            x.Data,
		Signature:       "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *PayloadAttestation) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		AggregationBits string                  `json:"aggregation_bits"`
		Data            *PayloadAttestationData `json:"data"`
		Signature       string                  `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.AggregationBits, "0x")); err != nil {
		return err
	} else {
		x.AggregationBits = bitfield.Bitvector512(b)
	}
	x.Data = o.Data
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *PayloadAttestationData) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		BeaconBlockRoot   string `json:"beacon_block_root"`
		Slot              string `json:"slot"`
		PayloadPresent    bool   `json:"payload_present"`
		BlobDataAvailable bool   `json:"blob_data_available"`
	}
	o := &jsonObj{
		BeaconBlockRoot:   "0x" + hex.EncodeToString(x.BeaconBlockRoot),
		Slot:              fmt.Sprintf("%d", x.Slot),
		PayloadPresent:    x.PayloadPresent,
		BlobDataAvailable: x.BlobDataAvailable,
	}
	return json.Marshal(o)
}

func (x *PayloadAttestationData) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		BeaconBlockRoot   string `json:"beacon_block_root"`
		Slot              string `json:"slot"`
		PayloadPresent    bool   `json:"payload_present"`
		BlobDataAvailable bool   `json:"blob_data_available"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.BeaconBlockRoot, "0x")); err != nil {
		return err
	} else {
		x.BeaconBlockRoot = b
	}
	if v, err := strconv.ParseUint(o.Slot, 10, 64); err != nil {
		return err
	} else {
		x.Slot = primitives.Slot(v)
	}
	x.PayloadPresent = o.PayloadPresent
	x.BlobDataAvailable = o.BlobDataAvailable
	return nil
}

func (x *ExecutionPayloadBid) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		ParentBlockHash    string   `json:"parent_block_hash"`
		ParentBlockRoot    string   `json:"parent_block_root"`
		BlockHash          string   `json:"block_hash"`
		PrevRandao         string   `json:"prev_randao"`
		FeeRecipient       string   `json:"fee_recipient"`
		GasLimit           string   `json:"gas_limit"`
		BuilderIndex       string   `json:"builder_index"`
		Slot               string   `json:"slot"`
		Value              string   `json:"value"`
		ExecutionPayment   string   `json:"execution_payment"`
		BlobKzgCommitments []string `json:"blob_kzg_commitments"`
	}
	BlobKzgCommitmentsJSON := make([]string, len(x.BlobKzgCommitments))
	for i, v := range x.BlobKzgCommitments {
		BlobKzgCommitmentsJSON[i] = "0x" + hex.EncodeToString(v)
	}
	o := &jsonObj{
		ParentBlockHash:    "0x" + hex.EncodeToString(x.ParentBlockHash),
		ParentBlockRoot:    "0x" + hex.EncodeToString(x.ParentBlockRoot),
		BlockHash:          "0x" + hex.EncodeToString(x.BlockHash),
		PrevRandao:         "0x" + hex.EncodeToString(x.PrevRandao),
		FeeRecipient:       "0x" + hex.EncodeToString(x.FeeRecipient),
		GasLimit:           fmt.Sprintf("%d", x.GasLimit),
		BuilderIndex:       fmt.Sprintf("%d", x.BuilderIndex),
		Slot:               fmt.Sprintf("%d", x.Slot),
		Value:              fmt.Sprintf("%d", x.Value),
		ExecutionPayment:   fmt.Sprintf("%d", x.ExecutionPayment),
		BlobKzgCommitments: BlobKzgCommitmentsJSON,
	}
	return json.Marshal(o)
}

func (x *ExecutionPayloadBid) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		ParentBlockHash    string   `json:"parent_block_hash"`
		ParentBlockRoot    string   `json:"parent_block_root"`
		BlockHash          string   `json:"block_hash"`
		PrevRandao         string   `json:"prev_randao"`
		FeeRecipient       string   `json:"fee_recipient"`
		GasLimit           string   `json:"gas_limit"`
		BuilderIndex       string   `json:"builder_index"`
		Slot               string   `json:"slot"`
		Value              string   `json:"value"`
		ExecutionPayment   string   `json:"execution_payment"`
		BlobKzgCommitments []string `json:"blob_kzg_commitments"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.ParentBlockHash, "0x")); err != nil {
		return err
	} else {
		x.ParentBlockHash = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.ParentBlockRoot, "0x")); err != nil {
		return err
	} else {
		x.ParentBlockRoot = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.BlockHash, "0x")); err != nil {
		return err
	} else {
		x.BlockHash = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.PrevRandao, "0x")); err != nil {
		return err
	} else {
		x.PrevRandao = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.FeeRecipient, "0x")); err != nil {
		return err
	} else {
		x.FeeRecipient = b
	}
	if v, err := strconv.ParseUint(o.GasLimit, 10, 64); err != nil {
		return err
	} else {
		x.GasLimit = v
	}
	if v, err := strconv.ParseUint(o.BuilderIndex, 10, 64); err != nil {
		return err
	} else {
		x.BuilderIndex = primitives.BuilderIndex(v)
	}
	if v, err := strconv.ParseUint(o.Slot, 10, 64); err != nil {
		return err
	} else {
		x.Slot = primitives.Slot(v)
	}
	if v, err := strconv.ParseUint(o.Value, 10, 64); err != nil {
		return err
	} else {
		x.Value = primitives.Gwei(v)
	}
	if v, err := strconv.ParseUint(o.ExecutionPayment, 10, 64); err != nil {
		return err
	} else {
		x.ExecutionPayment = primitives.Gwei(v)
	}
	x.BlobKzgCommitments = make([][]byte, len(o.BlobKzgCommitments))
	for i, s := range o.BlobKzgCommitments {
		b, err := hex.DecodeString(strings.TrimPrefix(s, "0x"))
		if err != nil {
			return err
		}
		x.BlobKzgCommitments[i] = b
	}
	return nil
}

func (x *SignedExecutionPayloadBid) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Message   *ExecutionPayloadBid `json:"message"`
		Signature string               `json:"signature"`
	}
	o := &jsonObj{
		Message:   x.Message,
		Signature: "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SignedExecutionPayloadBid) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Message   *ExecutionPayloadBid `json:"message"`
		Signature string               `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Message = o.Message
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *Builder) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Pubkey            string `json:"pubkey"`
		Version           string `json:"version"`
		ExecutionAddress  string `json:"execution_address"`
		Balance           string `json:"balance"`
		DepositEpoch      string `json:"deposit_epoch"`
		WithdrawableEpoch string `json:"withdrawable_epoch"`
	}
	o := &jsonObj{
		Pubkey:            "0x" + hex.EncodeToString(x.Pubkey),
		Version:           "0x" + hex.EncodeToString(x.Version),
		ExecutionAddress:  "0x" + hex.EncodeToString(x.ExecutionAddress),
		Balance:           fmt.Sprintf("%d", x.Balance),
		DepositEpoch:      fmt.Sprintf("%d", x.DepositEpoch),
		WithdrawableEpoch: fmt.Sprintf("%d", x.WithdrawableEpoch),
	}
	return json.Marshal(o)
}

func (x *Builder) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Pubkey            string `json:"pubkey"`
		Version           string `json:"version"`
		ExecutionAddress  string `json:"execution_address"`
		Balance           string `json:"balance"`
		DepositEpoch      string `json:"deposit_epoch"`
		WithdrawableEpoch string `json:"withdrawable_epoch"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Pubkey, "0x")); err != nil {
		return err
	} else {
		x.Pubkey = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Version, "0x")); err != nil {
		return err
	} else {
		x.Version = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.ExecutionAddress, "0x")); err != nil {
		return err
	} else {
		x.ExecutionAddress = b
	}
	if v, err := strconv.ParseUint(o.Balance, 10, 64); err != nil {
		return err
	} else {
		x.Balance = primitives.Gwei(v)
	}
	if v, err := strconv.ParseUint(o.DepositEpoch, 10, 64); err != nil {
		return err
	} else {
		x.DepositEpoch = primitives.Epoch(v)
	}
	if v, err := strconv.ParseUint(o.WithdrawableEpoch, 10, 64); err != nil {
		return err
	} else {
		x.WithdrawableEpoch = primitives.Epoch(v)
	}
	return nil
}

func (x *BuilderPendingPayment) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Weight     string                    `json:"weight"`
		Withdrawal *BuilderPendingWithdrawal `json:"withdrawal"`
	}
	o := &jsonObj{
		Weight:     fmt.Sprintf("%d", x.Weight),
		Withdrawal: x.Withdrawal,
	}
	return json.Marshal(o)
}

func (x *BuilderPendingPayment) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Weight     string                    `json:"weight"`
		Withdrawal *BuilderPendingWithdrawal `json:"withdrawal"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.Weight, 10, 64); err != nil {
		return err
	} else {
		x.Weight = primitives.Gwei(v)
	}
	x.Withdrawal = o.Withdrawal
	return nil
}

func (x *BuilderPendingWithdrawal) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		FeeRecipient string `json:"fee_recipient"`
		Amount       string `json:"amount"`
		BuilderIndex string `json:"builder_index"`
	}
	o := &jsonObj{
		FeeRecipient: "0x" + hex.EncodeToString(x.FeeRecipient),
		Amount:       fmt.Sprintf("%d", x.Amount),
		BuilderIndex: fmt.Sprintf("%d", x.BuilderIndex),
	}
	return json.Marshal(o)
}

func (x *BuilderPendingWithdrawal) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		FeeRecipient string `json:"fee_recipient"`
		Amount       string `json:"amount"`
		BuilderIndex string `json:"builder_index"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.FeeRecipient, "0x")); err != nil {
		return err
	} else {
		x.FeeRecipient = b
	}
	if v, err := strconv.ParseUint(o.Amount, 10, 64); err != nil {
		return err
	} else {
		x.Amount = primitives.Gwei(v)
	}
	if v, err := strconv.ParseUint(o.BuilderIndex, 10, 64); err != nil {
		return err
	} else {
		x.BuilderIndex = primitives.BuilderIndex(v)
	}
	return nil
}

func (x *SyncCommitteeMessage) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Slot           string `json:"slot"`
		BlockRoot      string `json:"beacon_block_root"`
		ValidatorIndex string `json:"validator_index"`
		Signature      string `json:"signature"`
	}
	o := &jsonObj{
		Slot:           fmt.Sprintf("%d", x.Slot),
		BlockRoot:      "0x" + hex.EncodeToString(x.BlockRoot),
		ValidatorIndex: fmt.Sprintf("%d", x.ValidatorIndex),
		Signature:      "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SyncCommitteeMessage) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Slot           string `json:"slot"`
		BlockRoot      string `json:"beacon_block_root"`
		ValidatorIndex string `json:"validator_index"`
		Signature      string `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.Slot, 10, 64); err != nil {
		return err
	} else {
		x.Slot = primitives.Slot(v)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.BlockRoot, "0x")); err != nil {
		return err
	} else {
		x.BlockRoot = b
	}
	if v, err := strconv.ParseUint(o.ValidatorIndex, 10, 64); err != nil {
		return err
	} else {
		x.ValidatorIndex = primitives.ValidatorIndex(v)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *BeaconBlockAltair) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Slot          string                 `json:"slot"`
		ProposerIndex string                 `json:"proposer_index"`
		ParentRoot    string                 `json:"parent_root"`
		StateRoot     string                 `json:"state_root"`
		Body          *BeaconBlockBodyAltair `json:"body"`
	}
	o := &jsonObj{
		Slot:          fmt.Sprintf("%d", x.Slot),
		ProposerIndex: fmt.Sprintf("%d", x.ProposerIndex),
		ParentRoot:    "0x" + hex.EncodeToString(x.ParentRoot),
		StateRoot:     "0x" + hex.EncodeToString(x.StateRoot),
		Body:          x.Body,
	}
	return json.Marshal(o)
}

func (x *BeaconBlockAltair) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Slot          string                 `json:"slot"`
		ProposerIndex string                 `json:"proposer_index"`
		ParentRoot    string                 `json:"parent_root"`
		StateRoot     string                 `json:"state_root"`
		Body          *BeaconBlockBodyAltair `json:"body"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if v, err := strconv.ParseUint(o.Slot, 10, 64); err != nil {
		return err
	} else {
		x.Slot = primitives.Slot(v)
	}
	if v, err := strconv.ParseUint(o.ProposerIndex, 10, 64); err != nil {
		return err
	} else {
		x.ProposerIndex = primitives.ValidatorIndex(v)
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.ParentRoot, "0x")); err != nil {
		return err
	} else {
		x.ParentRoot = b
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.StateRoot, "0x")); err != nil {
		return err
	} else {
		x.StateRoot = b
	}
	x.Body = o.Body
	return nil
}

func (x *BeaconBlockBodyAltair) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		RandaoReveal      string                 `json:"randao_reveal"`
		Eth1Data          *Eth1Data              `json:"eth1_data"`
		Graffiti          string                 `json:"graffiti"`
		ProposerSlashings []*ProposerSlashing    `json:"proposer_slashings"`
		AttesterSlashings []*AttesterSlashing    `json:"attester_slashings"`
		Attestations      []*Attestation         `json:"attestations"`
		Deposits          []*Deposit             `json:"deposits"`
		VoluntaryExits    []*SignedVoluntaryExit `json:"voluntary_exits"`
		SyncAggregate     *SyncAggregate         `json:"sync_aggregate"`
	}
	o := &jsonObj{
		RandaoReveal:      "0x" + hex.EncodeToString(x.RandaoReveal),
		Eth1Data:          x.Eth1Data,
		Graffiti:          "0x" + hex.EncodeToString(x.Graffiti),
		ProposerSlashings: x.ProposerSlashings,
		AttesterSlashings: x.AttesterSlashings,
		Attestations:      x.Attestations,
		Deposits:          x.Deposits,
		VoluntaryExits:    x.VoluntaryExits,
		SyncAggregate:     x.SyncAggregate,
	}
	return json.Marshal(o)
}

func (x *BeaconBlockBodyAltair) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		RandaoReveal      string                 `json:"randao_reveal"`
		Eth1Data          *Eth1Data              `json:"eth1_data"`
		Graffiti          string                 `json:"graffiti"`
		ProposerSlashings []*ProposerSlashing    `json:"proposer_slashings"`
		AttesterSlashings []*AttesterSlashing    `json:"attester_slashings"`
		Attestations      []*Attestation         `json:"attestations"`
		Deposits          []*Deposit             `json:"deposits"`
		VoluntaryExits    []*SignedVoluntaryExit `json:"voluntary_exits"`
		SyncAggregate     *SyncAggregate         `json:"sync_aggregate"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	if b, err := hex.DecodeString(strings.TrimPrefix(o.RandaoReveal, "0x")); err != nil {
		return err
	} else {
		x.RandaoReveal = b
	}
	x.Eth1Data = o.Eth1Data
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Graffiti, "0x")); err != nil {
		return err
	} else {
		x.Graffiti = b
	}
	x.ProposerSlashings = o.ProposerSlashings
	x.AttesterSlashings = o.AttesterSlashings
	x.Attestations = o.Attestations
	x.Deposits = o.Deposits
	x.VoluntaryExits = o.VoluntaryExits
	x.SyncAggregate = o.SyncAggregate
	return nil
}

func (x *SignedBeaconBlockAltair) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Block     *BeaconBlockAltair `json:"message"`
		Signature string             `json:"signature"`
	}
	o := &jsonObj{
		Block:     x.Block,
		Signature: "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SignedBeaconBlockAltair) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Block     *BeaconBlockAltair `json:"message"`
		Signature string             `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Block = o.Block
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}

func (x *SignedBeaconBlock) MarshalJSON() ([]byte, error) {
	type jsonObj struct {
		Block     *BeaconBlock `json:"message"`
		Signature string       `json:"signature"`
	}
	o := &jsonObj{
		Block:     x.Block,
		Signature: "0x" + hex.EncodeToString(x.Signature),
	}
	return json.Marshal(o)
}

func (x *SignedBeaconBlock) UnmarshalJSON(data []byte) error {
	type jsonObj struct {
		Block     *BeaconBlock `json:"message"`
		Signature string       `json:"signature"`
	}
	var o jsonObj
	if err := json.Unmarshal(data, &o); err != nil {
		return err
	}
	x.Block = o.Block
	if b, err := hex.DecodeString(strings.TrimPrefix(o.Signature, "0x")); err != nil {
		return err
	} else {
		x.Signature = b
	}
	return nil
}
