name: Check log.go files
on: [ pull_request ]

jobs:
  check-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go 1.25.1
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Install ripgrep
        run: sudo apt-get install -y ripgrep

      - name: Check log.go files
        run: ./hack/check-logs.sh
