name: Bazel Unit Tests

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: syjn99/bazel-toolchain:latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Run tests
        run: |
          bazel test \
            --config=unit-test \
            -- //... -//testing/endtoend/...
