name: Bazel Unit Tests

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: syjn99/bazel-toolchain:latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 390.0.0"

      - name: Run tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.gcp-auth.outputs.credentials_file_path }}
        run: |
          bazel test \
            --host_jvm_args=-Xmx4g \
            --config=unit-test \
            -- //... -//testing/endtoend/...
